# Generated by Django 4.1.3 on 2022-12-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='L_LINESTATUS',
            field=models.CharField(choices=[('1', '待支付'), ('2', '已支付')], default=1, help_text='明细状态', max_length=1, verbose_name='明细状态'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='L_RETURNFLAG',
            field=models.CharField(choices=[('1', '正常交易'), ('2', '退货')], default=1, help_text='是否退货', max_length=1, verbose_name='是否退货'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='O_ORDERSTATUS',
            field=models.CharField(choices=[('1', '待支付'), ('2', '已支付')], default=1, help_text='订单状态', max_length=1, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='partsupp',
            name='PS_AVAILQTY',
            field=models.FloatField(help_text='供应数量', verbose_name='供应数量'),
        ),
    ]
