# Generated by Django 4.1.3 on 2022-12-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_lineitem_l_linestatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='O_SHIPPRIORITY',
            field=models.IntegerField(choices=[(1, ' 一级'), (2, ' 二级'), (3, ' 三级'), (4, ' 四级')], help_text='运输优先级', verbose_name='运输优先级'),
        ),
    ]
