# Generated by Django 4.1.3 on 2022-12-05 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_orders_o_orderpriority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='L_ORDERKEY',
            field=models.OneToOneField(help_text='订单号,外键O_ORDERKEY。与L_LINENUMBER联合构成主键', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LO_ORDERKEY', to='catalog.orders', verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='O_ORDERPRIORITY',
            field=models.CharField(choices=[('1', ' 一级'), ('2', ' 二级'), ('3', ' 三级'), ('4', ' 四级')], default='1', help_text='优先级', max_length=1, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='O_SHIPPRIORITY',
            field=models.CharField(choices=[('1', ' 一级'), ('2', ' 二级'), ('3', ' 三级'), ('4', ' 四级')], default='1', help_text='运输优先级', max_length=1, verbose_name='运输优先级'),
        ),
    ]
