# Generated by Django 4.1.3 on 2022-12-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_lineitem_l_orderkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='L_SHIPMODE',
            field=models.CharField(help_text='运输方式', max_length=1, verbose_name='运输方式'),
        ),
    ]
