# Generated by Django 4.1.3 on 2022-12-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_lineitem_l_shipmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='L_SHIPMODE',
            field=models.CharField(choices=[('1', ' 陆运'), ('2', ' 海运'), ('3', ' 空运')], default='1', help_text='运输方式', max_length=1, verbose_name='运输方式'),
        ),
    ]
