# Generated by Django 4.1.3 on 2022-12-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_lineitem_l_shipmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='L_EXTENDEDPRICE',
            field=models.FloatField(default=0, help_text='总金额', verbose_name='总金额'),
        ),
    ]
