# Generated by Django 4.1.3 on 2022-12-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_lineitem_l_extendedprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='O_TOTALPRICE',
            field=models.FloatField(help_text='订单金额', null=True, verbose_name='订单金额'),
        ),
    ]
