# Generated by Django 4.1.3 on 2022-12-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_orders_o_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='O_TOTALPRICE',
            field=models.FloatField(default=0, help_text='订单金额', verbose_name='订单金额'),
        ),
    ]
